version: '3.7'

services:

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iremono-backend-container-prod
    ports:
      - 5555:5555
    volumes:
      - ./iremono_media:/app/iremono_media:rw
      - ./.env.prod:/app/.env.prod:rw

    networks: [ 'iremono-prod' ]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: iremono-mysql-container-prod
    ports:
      - 3306:3306
    volumes:
      - ./packages/iremono-backend-core/scripts/mysql/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: thisisreallystrongpassword
      MYSQL_DATABASE: iremono_db
      MYSQL_USER: iremono
      MYSQL_PASSWORD: thisisreallystrongpassword
    networks: [ 'iremono-prod' ]

networks: { iremono-prod: { driver: bridge } }
